// <auto-generated />
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Backend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200813172059_Initial-Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");

            modelBuilder.Entity("Backend.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "lampadas.svg",
                            Title = "Lâmpadas"
                        },
                        new
                        {
                            Id = 2,
                            Image = "baterias.svg",
                            Title = "Pilhas e Baterias"
                        },
                        new
                        {
                            Id = 3,
                            Image = "papeis-papelao.svg",
                            Title = "Papéis e Papelão"
                        },
                        new
                        {
                            Id = 4,
                            Image = "eletronicos.svg",
                            Title = "Resíduos Eletrônicos"
                        },
                        new
                        {
                            Id = 5,
                            Image = "organicos.svg",
                            Title = "Resíduos Orgânicos"
                        },
                        new
                        {
                            Id = 6,
                            Image = "oleo.svg",
                            Title = "Óleo de Cozinha"
                        });
                });

            modelBuilder.Entity("Backend.Models.Point", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uf")
                        .HasColumnType("TEXT")
                        .HasMaxLength(2);

                    b.Property<string>("Whatsapp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Points");
                });

            modelBuilder.Entity("Backend.Models.PointItem", b =>
                {
                    b.Property<int>("PointId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PointId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("PointItems");
                });

            modelBuilder.Entity("Backend.Models.PointItem", b =>
                {
                    b.HasOne("Backend.Models.Item", "Item")
                        .WithMany("PointsItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Point", "Point")
                        .WithMany("PointsItems")
                        .HasForeignKey("PointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
